### ISSUE TITLE
The vid for videos used

### ISSUE THREAD

**Issue by jasonppy** [VanyaBK/visual_ASR_EC#1]
Thanks for the great work and open-source the toolkit.

Is it possible to share the vid of the dataset? I believe that will be much easier for people who want to follow up your work to give a fair comparison. (also the timestamps of the clips if you don't used the entire videos)

**Comment by VanyaBK** [comment]
Hi,
Thank you for your interest in our work. Unfortunately we are unable to release the video links due to legal compliance issues. Although we cannot open-source the exact dataset, we obtained these links using the youtube-dl toolkit by filtering the videos which have human-annotated transcripts in English as well as the audio in English language, as mentioned in our paper. This should help you in obtaining the video links.

**Comment by VanyaBK** [comment]
Hi,
Thank you for your interest in our work. I have uploaded the youtube links which were used. The whole of the video was used  in our dataset

**Comment by jasonppy** [comment]
Thank you for the help. From the file I can see that there are 148k videos, while in the paper it says 127k samples are used (after sentence-bert filtering) so I just want to make sure whether the links are the set after filtering

**Comment by VanyaBK** [comment]
The links I have posted are before filtering. 127k samples are not the number of videos but the number of parallel sentences pairs(of correct and incorrect sentences) along with images. Hope this answers your question

**Comment by jasonppy** [comment]
Very helpful, thanks
